[package]
name = "piddle"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
hecs = "0.6.3"
lazy_static = "1.4.0"
nom = "7.0.0"
rustyline = "9.0.0"
string-interner = "0.13.0"
structopt = "0.3.22"
thiserror = "1.0.26"
